select *from MEMBER

select * from DETECTION_BOARD


 CREATE TABLE USERS_NBR (
	MBR_SHOP VARCHAR(20) NOT NULL,
	CCTV_NBR NUMBER NOT NULL,
	KIND NUMBER NOT NULL,
	USERS_NBR NUMBER NOT NULL,
	INDATE DATE DEFAULT SYSDATE
 )
 
select * from USERS_NBR

CREATE TABLE USERS_NBR (
	MBR_SHOP VARCHAR(20) NOT NULL,
	CCTV_NBR NUMBER NOT NULL,
	det_name VARCHAR(200) NOT NULL,
	INDATE DATE DEFAULT SYSDATE
 )


select * from DETECTION_BOARD

drop table DETECTION_BOARD

insert into DETECTION_BOARD(num,CCTV,content,VIDEO_PATH,PHOTO_PATH)
values(nbr_seq.nextval,1,' ','PATH','PATH');
DELETE FROM DETECTION_BOARD WHERE NUM=1
insert into USERS_NBR(MBR_SHOP,CCTV_NBR,USERS_NBR)
values('test',1,15);
nbr_seq.nextval
CREATE SEQUENCE NBR_SEQ INCREMENT BY 1 START WITH 1;

drop sequence nbr_seq;

CREATE TABLE DETECTION_BOARD (
	NUM NUMBER NOT NULL,
	CCTV NUMBER NOT NULL,	
	CONTENT VARCHAR2(500) NOT NULL,
	VIDEO_PATH VARCHAR2(100) NOT NULL,
	PHOTO_PATH VARCHAR2(100) NOT NULL,
	INDATE DATE DEFAULT SYSDATE NOT NULL,
	
 CONSTRAINT DETECTION_BOARD_NUM_PK PRIMARY KEY(NUM)
 )
SELECT MAX(NUM) FROM DETECTION_BOARD  
 RANK() OVER (ORDER BY SAL DESC) 
 update DETECTION_BOARD set VIDEO_PATH=:video WHERE EXISTS(SELECT * FROM DETECTION_BOARD  WHERE ROWNUM=1 ORDER BY NUM DESC)
 
 